branch-defaults:
  master:
    environment: quickjobs-dev
    group_suffix: null
environment-defaults:
  quickjobs-dev:
    branch: master
    repository: origin
global:
  application_name: quickjobs
  branch: master
  default_ec2_keyname: devops_sec_key_1
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
